version: '3.8'
networks:
  maze_net:

services:
  maze:
    build: .
    depends_on:
      - database
    networks:
      - maze_net
    environment:
      LOG_FORMAT: json
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 5000
      DB_URL: postgresql://maze:maze@maze:5432/maze_db?sslmode=disable&log_statement=all
      DB_TIMEOUT_SEC: 120
      DB_REFRESH_SEC: 5
    ports:
      - "5000:5000"

  database:
    image: postgres:alpine
    command: postgres -c 'max_connections=100'
    container_name: maze
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: maze_db
      POSTGRES_USER: maze
      POSTGRES_PASSWORD: maze
    networks:
      - maze_net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready, -U auth" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5432