// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Maze Game
//
//  Maze Game API
//  Schemes:
//    http
//  Host: localhost:5000
//  BasePath: /v1
//  Version: v1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
