// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetGameLevelIDParams creates a new GetGameLevelIDParams object
//
// There are no default values defined in the spec.
func NewGetGameLevelIDParams() GetGameLevelIDParams {

	return GetGameLevelIDParams{}
}

// GetGameLevelIDParams contains all the bound params for the get game level ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetGameLevelID
type GetGameLevelIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	LevelID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetGameLevelIDParams() beforehand.
func (o *GetGameLevelIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rLevelID, rhkLevelID, _ := route.Params.GetOK("levelId")
	if err := o.bindLevelID(rLevelID, rhkLevelID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindLevelID binds and validates parameter LevelID from path.
func (o *GetGameLevelIDParams) bindLevelID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("levelId", "path", "int64", raw)
	}
	o.LevelID = value

	return nil
}
