// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGameLevelIDHandlerFunc turns a function with the right signature into a get game level ID handler
type GetGameLevelIDHandlerFunc func(GetGameLevelIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGameLevelIDHandlerFunc) Handle(params GetGameLevelIDParams) middleware.Responder {
	return fn(params)
}

// GetGameLevelIDHandler interface for that can handle valid get game level ID params
type GetGameLevelIDHandler interface {
	Handle(GetGameLevelIDParams) middleware.Responder
}

// NewGetGameLevelID creates a new http.Handler for the get game level ID operation
func NewGetGameLevelID(ctx *middleware.Context, handler GetGameLevelIDHandler) *GetGameLevelID {
	return &GetGameLevelID{Context: ctx, Handler: handler}
}

/* GetGameLevelID swagger:route GET /game/{levelId} getGameLevelId

Play game by LevelId

*/
type GetGameLevelID struct {
	Context *middleware.Context
	Handler GetGameLevelIDHandler
}

func (o *GetGameLevelID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGameLevelIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
