// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetLevelLevelIDHandlerFunc turns a function with the right signature into a get level level ID handler
type GetLevelLevelIDHandlerFunc func(GetLevelLevelIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLevelLevelIDHandlerFunc) Handle(params GetLevelLevelIDParams) middleware.Responder {
	return fn(params)
}

// GetLevelLevelIDHandler interface for that can handle valid get level level ID params
type GetLevelLevelIDHandler interface {
	Handle(GetLevelLevelIDParams) middleware.Responder
}

// NewGetLevelLevelID creates a new http.Handler for the get level level ID operation
func NewGetLevelLevelID(ctx *middleware.Context, handler GetLevelLevelIDHandler) *GetLevelLevelID {
	return &GetLevelLevelID{Context: ctx, Handler: handler}
}

/* GetLevelLevelID swagger:route GET /level/{levelId} getLevelLevelId

Level by LevelId

*/
type GetLevelLevelID struct {
	Context *middleware.Context
	Handler GetLevelLevelIDHandler
}

func (o *GetLevelLevelID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLevelLevelIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
