// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LevelRequest level request
//
// swagger:model LevelRequest
type LevelRequest struct {
	Level
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *LevelRequest) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Level
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Level = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m LevelRequest) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.Level)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this level request
func (m *LevelRequest) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Level
	if err := m.Level.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this level request based on the context it is used
func (m *LevelRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Level
	if err := m.Level.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *LevelRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LevelRequest) UnmarshalBinary(b []byte) error {
	var res LevelRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
